[build]
  command = "npm run build"
  publish = "dist"
  functions = "api"

[dev]
  command = "npm run dev"
  functions = "api"
  publish = "dist"
  port = 8888
  targetPort = 5173

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 